### PR TITLE
refactor: refactor chain_of_thought_agent for better readability and maintainability

### PR DESCRIPTION
**Pull request by foreverLoveWisdom**
- refactor chain_of_thought_agent for better readability and maintainability 🏗️

### CODE REVIEW

**Comment by andreibondarev** [comment]
@foreverLoveWisdom `standardrb --fix` should fix a bunch of linting issues.

**Comment by foreverLoveWisdom** [comment]
> @foreverLoveWisdom `standardrb --fix` should fix a bunch of linting issues.

- Thank you for your suggestion. I re-run it, but all the errors are from the new hash syntax of Ruby 3 😄 So, it can't fix them. I will update it later today. Btw, this is my first PR. So, please feel free to let me know if there are things for improvements 🙏  I am flexible and open to suggestions 😄

**Comment by foreverLoveWisdom** [comment]
Sorry 😢 , I accidentally made a mistake when forking this repo(I should have cloned it under a different account). I need to close this PR and will open another PR later

**Comment by andreibondarev** [comment]
@foreverLoveWisdom Please do reopen the PR!

**Pull request closed without merging**
